### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xab'

### ISSUE THREAD

**Issue by LyashenkoGS** [Teebytes/TnT-Fuzzer#10]
**Prerequisites:**
JDK 1.8
Apache Maven 3.3.9 
TnT_Fuzzer v1.0.0
Ubuntu 16.04
Application under test: https://github.com/springframeworkguru/springboot_swagger_example/commit/e41186ecfae6c6436740f4da6982d3cf4fb79753

**How to reproduce:**

**To build and run execute the application under test:**
mvn clean install && java -jar target/spring-boot-web-*.jar 

**Actual behavior:**

` vagrant@ubuntu-xenial:~/springboot_swagger_example$

 tntfuzzer --url http://localhost:8080/v2/api-docs --log_all
___________  ___________     ___________
\__    ___/__\__    ___/     \_   _____/_ __________________ ___________ 
  |    | /    \|    |  ______ |    __)|  |  \___   /\___   // __ \_  __ \
  |    ||   |  \    | /_____/ |     \ |  |  //    /  /    /\  ___/|  | \/
  |____||___|  /____|         \___  / |____//_____ \/_____ \\___  >__|   
    Dynamite \/ for your API!     \/              \/      \/    \/       v1.0.0

Fetching open API from: http://localhost:8080/v2/api-docs
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/tntfuzzer", line 11, in <module>
    sys.exit(main())
  File "/home/vagrant/.local/lib/python2.7/site-packages/tntfuzzer/tntfuzzer.py", line 86, in main
    tnt.start()
  File "/home/vagrant/.local/lib/python2.7/site-packages/tntfuzzer/tntfuzzer.py", line 22, in start
    client = SwaggerClient.from_url(self.url)
  File "/home/vagrant/.local/lib/python2.7/site-packages/bravado/client.py", line 124, in from_url
    return cls.from_spec(spec_dict, spec_url, http_client, config)
  File "/home/vagrant/.local/lib/python2.7/site-packages/bravado/client.py", line 145, in from_spec
    spec_dict, origin_url, http_client, config)
  File "/home/vagrant/.local/lib/python2.7/site-packages/bravado_core/spec.py", line 170, in from_dict
    spec.build()
  File "/home/vagrant/.local/lib/python2.7/site-packages/bravado_core/spec.py", line 192, in build
    swagger_spec=self,
  File "/home/vagrant/.local/lib/python2.7/site-packages/bravado_core/spec.py", line 499, in post_process_spec
    descend(swagger_spec.spec_dict)
  File "/home/vagrant/.local/lib/python2.7/site-packages/bravado_core/spec.py", line 492, in descend
    descend(fragment[key], path + [key], visited_refs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/bravado_core/spec.py", line 491, in descend
    fire_callbacks(fragment, key, path + [key])
  File "/home/vagrant/.local/lib/python2.7/site-packages/bravado_core/spec.py", line 458, in fire_callbacks
    callback(container, key, path)
  File "/home/vagrant/.local/lib/python2.7/site-packages/bravado_core/model.py", line 43, in tag_models
    log.debug('Found model: {0}'.format(model_name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xab' in position 8: ordinal not in range(128)
`

**Comment by Thoiz** [comment]
Hi @LyashenkoGS,

Thanks for submitting this issue. Unfortunately, the cause of the problem seems to be the 'bravado' dependency we are using for reading in the swagger/openapi specification. We want to remove bravado in the next release anyway and will fix this issue with that.

**Comment by xenobyte** [comment]
Should be fixed by 771f20bf6054ec5043e4eda85f418d469d62a933
