### ISSUE TITLE
AttributeError: 'module' object has no attribute 'JSONDecodeError'

### ISSUE THREAD

**Issue by SpeTr0x** [Teebytes/TnT-Fuzzer#47]
Traceback (most recent call last):
  File "tntfuzzer.py", line 223, in <module>
    main()
  File "tntfuzzer.py", line 217, in main
    tnt.start()
  File "tntfuzzer.py", line 56, in start
    except json.JSONDecodeError:
AttributeError: 'module' object has no attribute 'JSONDecodeError'

**Comment by SpeTr0x** [comment]
[SOLVED]
add this line to imports 
`import simplejson`

then change line 53 from 
        `except json.JSONDecodeError:`
to 
`        except simplejson.JSONDecodeError:`
