### ISSUE TITLE
Installation fail on module PyJFuzz

### ISSUE THREAD

**Issue by FaeeLoL** [Teebytes/TnT-Fuzzer#50]
```
# pip3 install tntfuzzer
Collecting tntfuzzer
  Downloading https://files.pythonhosted.org/packages/d9/f6/b61cbdd5767d428c1cd69509b9f362f4353dfb5b63abec9a34419a851be9/tntfuzzer-1.0.0.tar.gz
Collecting GitPython==2.1.5 (from tntfuzzer)
  Downloading https://files.pythonhosted.org/packages/7e/13/2a556eb97dcf498c915e5e04bb82bf74e07bb8b7337ca2be49bfd9fb6313/GitPython-2.1.5-py2.py3-none-any.whl (443kB)
    100% |████████████████████████████████| 450kB 2.7MB/s 
Collecting PyJFuzz==1.1.0 (from tntfuzzer)
  Using cached https://files.pythonhosted.org/packages/14/19/214133aed1469969c0797bc74335350b061a2e55955e299bf7621aa21904/PyJFuzz-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-t844pnfs/PyJFuzz/setup.py", line 25, in <module>
        import commands
    ModuleNotFoundError: No module named 'commands'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-t844pnfs/PyJFuzz/
```

Installation of pyjfuzz using pip gives the same problem.

**Comment by xenobyte** [comment]
Did you try this?

```
git clone https://github.com/mseclab/PyJFuzz.git && cd PyJFuzz && python setup.py install
cd ..
pip install -r requirements.txt
```
